# -*- coding: utf-8 -*-
"""Regenerates src/RefData.Generated.cs from ../VanillaDump.

Run from the Tool/ directory:  python tools/gen_refdata.py
Re-run after any game update + fresh dump (see PACKTOOL_DESIGN.md).
"""
import io, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
TOOL = os.path.dirname(HERE)
DUMP = os.path.join(os.path.dirname(TOOL), "VanillaDump")
OUT = os.path.join(TOOL, "src", "RefData.Generated.cs")


def parse_dump_lists(path):
    """'### Name (N)' sections with two-space-indented lines."""
    pools, cur = {}, None
    for line in io.open(path, encoding="utf-8", errors="replace"):
        m = re.match(r"^### (\w+) \((\d+|NULL)\)", line)
        if m:
            cur = m.group(1)
            pools[cur] = []
            continue
        if cur is not None:
            if line.startswith("  ") and line.strip():
                pools[cur].append(line.rstrip("\n")[2:])
            elif line.strip() == "":
                pass
            else:
                cur = None
    return pools


def parse_topics(path):
    topics, cur, curlist = [], None, None
    for line in io.open(path, encoding="utf-8", errors="replace"):
        m = re.match(r"^---- Topic: (.+?) \((\w+)\) ----", line)
        if m:
            cur = {"name": m.group(1), "folder": m.group(2), "lists": {}}
            topics.append(cur)
            curlist = None
            continue
        if cur is not None:
            m2 = re.match(r"^### (\w+) \((\d+|NULL)\)", line)
            if m2:
                curlist = m2.group(1)
                cur["lists"][curlist] = []
                continue
            if line.startswith("  ") and line.strip() and curlist:
                cur["lists"][curlist].append(line.rstrip("\n")[2:])
    return topics


def parse_atlas(path):
    """Zone reference lines in 05: '  Scene -> "Display" | levels a-b | dungeon=X | ...'"""
    zones = []
    for line in io.open(path, encoding="utf-8", errors="replace"):
        m = re.match(r'^  (\S+)(?: -> "(.+?)")? \| levels (-?\d+)-(-?\d+) \| dungeon=(\w+)', line)
        if m:
            scene = m.group(1)
            disp = m.group(2) if m.group(2) else scene
            zones.append((scene, disp, int(m.group(3)), int(m.group(4)), m.group(5) == "True"))
    return zones


def parse_colors(path, label):
    for line in io.open(path, encoding="utf-8", errors="replace"):
        m = re.match(r"^" + label + r": (\d+) -> (.+)$", line.strip())
        if m:
            return re.findall(r"#([0-9A-Fa-f]{8})", m.group(2))
    return []


def parse_emojis(path):
    grab = False
    for line in io.open(path, encoding="utf-8", errors="replace"):
        if line.startswith("---- Emoji pool"):
            grab = True
            continue
        if grab and line.strip().startswith("["):
            inner = line.strip().strip("[]")
            return [p.strip() for p in inner.split("|") if p.strip()]
    return []


def cs_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    mgr = parse_dump_lists(os.path.join(DUMP, "01_manager_pools.txt"))
    glob = parse_dump_lists(os.path.join(DUMP, "02_global_language.txt"))
    guild = parse_dump_lists(os.path.join(DUMP, "06_guild_pools.txt"))
    post = parse_dump_lists(os.path.join(DUMP, "05_post_load.txt"))  # grouping pools live here
    topics = parse_topics(os.path.join(DUMP, "07_guild_topics.txt"))
    atlas = parse_atlas(os.path.join(DUMP, "05_post_load.txt"))
    env = os.path.join(DUMP, "00_environment.txt")
    hair = parse_colors(env, "HairColors")
    skin = parse_colors(env, "SkinColors")
    emojis = parse_emojis(env)

    # Template (blank) language list counts, from the 00 summary line.
    template_counts = {}
    for line in io.open(env, encoding="utf-8", errors="replace"):
        m = re.match(r"^\s*language list counts: (.+)$", line)
        if m:
            for pair in m.group(1).split():
                k, _, v = pair.partition("=")
                if v.isdigit():
                    template_counts[k] = int(v)
            break

    listen_pools = [
        "Obscenities", "GroupRequest", "LFGs", "JoinMyGuild", "JoinYourGuild",
        "WhereDidYouGet", "InfoWanted", "HelpReq", "InvisReq", "LocReq",
        "LevelCheck", "Gratitude", "Apologies", "WhatsUp", "Goodnight",
        "Declinations", "GenericGreeting", "Affirmations", "LevelUpCelebrations",
    ]

    grouping_names = ["Hellos", "Goodbyes", "Affirms", "Targeting", "Angry", "Lost"]

    w = io.StringIO()
    w.write("// GENERATED by tools/gen_refdata.py from ../VanillaDump - DO NOT EDIT BY HAND.\n")
    w.write("// Re-run after a game update + fresh dump.\n")
    w.write("using System.Collections.Generic;\n\nnamespace PackStudio\n{\n")
    w.write("    internal static class RefGen\n    {\n")

    # vanilla listen pool contents
    w.write("        internal static readonly Dictionary<string, string[]> VanillaListen = new Dictionary<string, string[]>\n        {\n")
    for p in listen_pools:
        lines = mgr.get(p, [])
        w.write("            { %s, new string[] { %s } },\n" % (cs_str(p), ", ".join(cs_str(x) for x in lines)))
    w.write("        };\n\n")

    # vanilla topic trigger corpus
    w.write("        internal static readonly VanillaTopic[] VanillaTopics = new[]\n        {\n")
    for t in topics:
        trig = t["lists"].get("ActivationWords", [])
        w.write("            new VanillaTopic(%s, %s, new string[] { %s }),\n"
                % (cs_str(t["name"]), cs_str(t["folder"]), ", ".join(cs_str(x) for x in trig)))
    w.write("        };\n\n")

    # pool sizes for dilution notes
    w.write("        internal static readonly Dictionary<string, int> PoolSizes = new Dictionary<string, int>\n        {\n")
    for prefix, pools in (("Manager", mgr), ("Global", glob), ("Guild", guild)):
        for name, lines in sorted(pools.items()):
            w.write("            { %s, %d },\n" % (cs_str(prefix + "." + name), len(lines)))
    for name in grouping_names:
        if name in post:
            w.write("            { %s, %d },\n" % (cs_str("Grouping." + name), len(post[name])))
    for name, count in sorted(template_counts.items()):
        w.write("            { %s, %d },\n" % (cs_str("Template." + name), count))
    w.write("        };\n\n")

    # atlas basics (display names here are GetZoneTerm-based; RefData.cs overrides
    # the 13 known-wrong ones with dump-verified runtime names)
    w.write("        internal static readonly ZoneEntry[] Atlas = new[]\n        {\n")
    for scene, disp, lo, hi, dungeon in atlas:
        w.write("            new ZoneEntry(%s, %s, %d, %d, %s),\n"
                % (cs_str(scene), cs_str(disp), lo, hi, "true" if dungeon else "false"))
    w.write("        };\n\n")

    # vanilla ambient-chatter counts per zone (dumped pre-injection).
    zone_counts = {}
    zdir = os.path.join(DUMP, "zones")
    if os.path.isdir(zdir):
        for fn in sorted(os.listdir(zdir)):
            if not fn.endswith(".txt"):
                continue
            scene = fn[:-4]
            in_comments = False
            for line in io.open(os.path.join(zdir, fn), encoding="utf-8", errors="replace"):
                if line.startswith("---- ZoneComments"):
                    in_comments = True
                    continue
                if in_comments:
                    m = re.match(r"^count: (\d+)", line.strip())
                    if m:
                        zone_counts[scene] = int(m.group(1))
                    break
    w.write("        internal static readonly Dictionary<string, int> ZoneChatterCounts = new Dictionary<string, int>\n        {\n")
    for scene in sorted(zone_counts):
        w.write("            { %s, %d },\n" % (cs_str(scene), zone_counts[scene]))
    w.write("        };\n\n")

    # example lines per pool (ghost placeholders + guidance examples).
    env_pools = parse_dump_lists(env)  # blank-template language full contents
    examples = {}
    for prefix, pools in (("Global", glob), ("Manager", mgr), ("Guild", guild)):
        for name, lines in pools.items():
            if lines:
                examples[prefix + "." + name] = lines[:3]
    for name in grouping_names:
        if post.get(name):
            examples["Grouping." + name] = post[name][:3]
    for name, lines in env_pools.items():
        if lines:
            examples.setdefault("Template." + name, lines[:3])
    w.write("        internal static readonly Dictionary<string, string[]> ExampleLines = new Dictionary<string, string[]>\n        {\n")
    for name in sorted(examples):
        w.write("            { %s, new string[] { %s } },\n" % (cs_str(name), ", ".join(cs_str(x) for x in examples[name])))
    w.write("        };\n\n")

    w.write("        internal static readonly string[] HairColors = { %s };\n" % ", ".join(cs_str(c) for c in hair))
    w.write("        internal static readonly string[] SkinColors = { %s };\n" % ", ".join(cs_str(c) for c in skin))
    w.write("        internal static readonly string[] Emojis = { %s };\n" % ", ".join(cs_str(c) for c in emojis))
    w.write("    }\n}\n")

    out = w.getvalue()
    if not os.path.isdir(os.path.dirname(OUT)):
        os.makedirs(os.path.dirname(OUT))
    io.open(OUT, "w", encoding="utf-8").write(out)
    print("wrote %s (%d listen pools, %d topics, %d atlas zones, %d/%d colors, %d emojis)"
          % (OUT, len(listen_pools), len(topics), len(atlas), len(hair), len(skin), len(emojis)))


if __name__ == "__main__":
    main()
